# Generated by Django 5.2.12 on 2026-05-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onlinevoting2026', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True, help_text='Party manifesto text'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='Onlinevoting2026.voter'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('admin', 'Admin'), ('candidate', 'Candidate')], default='voter', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'voter')},
        ),
    ]
